Close the cursor used to obtain cache size. Otherwise, we get a:
 sqlite3.OperationalError: unable to close due to unfinalised statements

when the DB is finally closed.